import { Result } from "./result"

export interface Page{
  page:number; //generated bu the queryparams page of user
  results: Result[];
  totalResults: number; //generated by results.length
  nsfw: boolean; //boolean map of default safesearch or query params safesearch 0=true 1=false 2=false
}
