version: "3.7"

services:
  backend:
    image: proyecto-final-back
    container_name: backend
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - SEARCH_API_URL=${SEARCH_API_URL}
    ports:
      - "52582:8000"
    networks:
      - proyecto-network

  frontend:
    image: proyecto-final-front
    container_name: frontend
    environment:
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - "52580:80"
    networks:
      - proyecto-network

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:7-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - proyecto-network
    volumes:
      - ./deploy/private/searxng-docker-new/valkey-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - proyecto-network
    ports:
      - "${SEARXNG_PORT}:8080"
    volumes:
      - ./deploy/private/searxng-docker-new/searxng:/etc/searxng:rw
      - ./deploy/private/searxng-docker-new/searxng/settings.yml:/usr/local/searxng/searx/settings.yml:ro
    command: >
      sh -c "echo \"${SETTINGS_SEARCH_XNG}\" > /usr/local/searxng/searx/settings.yml && echo \"${SETTINGS_SEARCH_XNG}\" > /etc/searxng/settings.yml"


    environment:
      - SEARXNG_BASE_URL=${SEARCH_API_URL}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  proyecto-network:
    driver: bridge

volumes:
  # caddy-data:
  caddy-config:
  valkey-data2:
